version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - mydb
    environment:
      - DB_HOST=db      # تأكد من أن هذا المتغير مضبوط بشكل صحيح
      - DB_NAME=mydb
      - DB_USER=root
      - DB_PASS=123

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - "/db:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mydb
    networks:
      - mydb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 123
    networks:
      - mydb

networks:
  mydb:
    driver: bridge

volumes:
  mysql:
